# Generated by Django 4.2 on 2023-10-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_auth_provider'),
        ('payment', '0002_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_id',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
