# Generated by Django 4.2.4 on 2023-09-01 13:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_deactivateuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsverification',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
