# Generated by Django 4.2.4 on 2023-09-22 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductViews',
        ),
    ]
